package main.cardgames.cardpack;

import java.util.ArrayList;

/**
 * A class representing a playing card, with a number and suit, as well as methods for printing the card(s) in a formatted way.
 * Used in the cardgames section of the TerminalGames app, with blackjava, textbasedholdem, and cribbage.
 * @todo - Maybe fix the data() method to be not static?
 * @author EmperorGrock
 */
public class Card {
	private int number;
	private int suit;
	private static final String top = "_______";
	private static final String bottom = "-------";
	private static final String middle = "|     |";
	//Spades, Clubs, Hearts, Diamond
	private final static String[] suits = {"\u2660", "\u2663", "\u2665", "\u2666"};
	//A-K, 0-12
	private final static String[] identity = {"A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"};

	/**
	 * Constructor for a card, which takes a number (0-12) and a suit (0-3) and initializes the card's properties accordingly.
	 * @param number The number of the card, where 0 = Ace, 1 = 2, ..., 9 = 10, 10 = Jack, 11 = Queen, 12 = King
	 * @param suit The suit of the card, where 0 = Spades, 1 = Clubs, 2 = Hearts, 3 = Diamonds
	 */
	Card(int number, int suit){
		this.number = number;
		this.suit = suit;
	}

	/**
	 * Default constructor for a card, which generates a random number and suit for the card.
	 * Note: This constructor is not used in the current implementation, as cards are typically generated by the Deck class, which ensures that there are no duplicate cards.
	 */
	Card(){
		this.number = (int)(Math.random()*13);
		this.suit = (int)(Math.random()*4);
	}

	/**
	 * Returns the number of the card.
	 * @return The number of the card
	 */
	public int getNum(){
		return this.number;
	}

	/**
	 * Returns the suit of the card.
	 * @return The suit of the card
	 */
	public int getSuit(){
		return this.suit;
	}

	/**
	 * Prints the back of the card.
	 */
	public static void printBack(){
		System.out.println(top);
		System.out.println("|/////|");
		System.out.println("|\\\\\\\\\\|");
		System.out.println("|/////|");
		System.out.println(bottom);
	}

	/**
	 * Returns a string of the middle section of the card, which includes the suit and number of the card, formatted for printing.
	 * @param c The card to generate the string for
	 * @return A string representing the middle section of the card, with the suit and number
	 */
	private static String data(Card c){
		if(c.number == 9) return ("| " + suits[c.suit] + identity[c.number] + " |");
		else return ("| " + suits[c.suit] + " " + identity[c.number] + " |");
	}

	/**
	 * Prints a single card in a formatted way, using the top, middle, and bottom strings to create a visual representation of the card.
	 */
	public void printCard(){
		System.out.println(top);
		System.out.println(data(this));
		System.out.println(middle);
		System.out.println(data(this));
		System.out.println(bottom);
	}

	public static void printCards(Card[] array){
		int max = array.length;
		for(int i = 0; i < max; i++){
			System.out.print(top + "   ");
		}
		System.out.println();
		for(Card i : array){
			System.out.print(data(i) + "   ");
		}
		System.out.println();
		for(int i = 0; i < max; i++){
			System.out.print(middle + "   ");
		}
		System.out.println();
		for(Card i : array){
			System.out.print(data(i) + "   ");
		}
		System.out.println();
		for(int i = 0; i < max; i++){
			System.out.print(bottom + "   ");
		}
		System.out.println();
	}

	public static void printCards(ArrayList<Card> array){
		int max = array.size();
		for(int i = 0; i < max; i++){
			System.out.print(top + "   ");
		}
		System.out.println();
		for(Card i : array){
			System.out.print(data(i) + "   ");
		}
		System.out.println();
		for(int i = 0; i < max; i++){
			System.out.print(middle + "   ");
		}
		System.out.println();
		for(Card i : array){
			System.out.print(data(i) + "   ");
		}
		System.out.println();
		for(int i = 0; i < max; i++){
			System.out.print(bottom + "   ");
		}
		System.out.println();
	}

	void main(String[] args){
		var n = new ArrayList<Card>();
		n.add(new Card(0, 0));
		n.add(new Card(12, 3));
		printCards(n);
	}
}
